### ISSUE TITLE
메인 페이지 기능 및 오류 수정 

### ISSUE THREAD

**Issue by OOixn** [CinEffi/frontend#120]
* 적용 페이지 : 메인 페이지

## 내용
메인 페이지 기능 및 오류 수정

## TODO
- [x] data가 null 일 경우 처리
- [x] 장르별 영화 목록이 null 일 경우 처리
- [x] 인기 평론이 null 일 경우 처리
- [x] 박스 오피스 제목 한 줄로 변경
- [x] 영화 클릭시 영화 상세 페이지로 이동
