### ISSUE TITLE
마이 페이지 추가 

### ISSUE THREAD

**Issue by koeunbeee** [CinEffi/frontend#41]
* 적용 페이지 : 마이페이지

## TODO
- [x] 마이페이지 css 수정
- [ ] 마이페이지 수정 모달
- [x] 내 컬렉션에서 삭제 확인 알럿, 변경 추가
