### ISSUE TITLE
마이페이지 변경

### ISSUE THREAD

**Issue by koeunbeee** [CinEffi/frontend#64]
* 적용 페이지 : 유저 페이지

## TODO
- [x] 마이페이지 유저페이지로 변경
- [x] 팔로우 버튼 생성
- [x] 정보 변경 모달 만들기
- [x] 회원정보 톱니바퀴 -> 로그아웃, 정보변경 버튼 만들기
